version: "3.9"

services:
  paperless-api-uploader:
    build: .                                # Build custom image once
    image: paperless-api-uploader
    container_name: paperless-api-uploader
    restart: unless-stopped
    user: "1000:1000"                       # <- use the UID/GID paperless runs as
    environment:
      TZ: America/Chicago
      PAPERLESS_URL:  "http://paperless.lan:8000"   # ← update if different
      PAPERLESS_TOKEN: "PUT-YOUR-TOKEN-HERE"        # ← generate in Paperless UI
      MIN_AGE: "60"            # wait 60 s after mtime before upload
      SCAN_INTERVAL: "300"     # scan every 5 min
      SOURCE_DIRS: "/nas/sharepoint;/nas/p21sftp"
      STATE_DB: "/state/uploaded.db"
    volumes:
      # *** READ-ONLY *** mounts of your original files
      - /volume1/doclinks/sharepoint:/nas/sharepoint:ro
      - /volume1/doclinks/p21sftp:/nas/p21sftp:ro

      # Folder that stores the tiny SQLite “already-uploaded” DB
      - /volume1/doclinks/apiuploader:/state
    # entrypoint provided by the Docker image
